Fix for poetry lock file, only update Podman version (#273)
We only want to lock the Podman to a specific version and update poetry
lock file accordingly. This PR will back out the additional dependency
updates.

This fixes the following error when workers fail to start up. 
I am not 100% sure of the root cause, but it is most likely tied to the
changes in django, djangoRQ, and RQ.

```
Traceback (most recent call last):
  File "/app/venv/bin/aap-eda-manage", line 6, in <module>
    sys.exit(main())
  File "/app/src/src/aap_eda/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/app/venv/lib64/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/app/venv/lib64/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/app/venv/lib64/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/app/venv/lib64/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/app/venv/lib64/python3.9/site-packages/django_rq/management/commands/rqworker.py", line 123, in handle
    w = get_worker(*args, **worker_kwargs)
  File "/app/venv/lib64/python3.9/site-packages/django_rq/workers.py", line 50, in get_worker
    return worker_class(
  File "/app/src/src/aap_eda/core/tasking/__init__.py", line 116, in __init__
    super().__init__(
  File "/app/venv/lib64/python3.9/site-packages/rq/worker.py", line 184, in __init__
    self.validate_queues()
  File "/app/venv/lib64/python3.9/site-packages/rq/worker.py", line 309, in validate_queues
    if not isinstance(queue, self.queue_class):
TypeError: isinstance() arg 2 must be a type or tuple of types
```